name: Deploy Quasar Front

on:
  push:
    branches:
      - main  # Déclenchement sur push dans main, adapte selon ta branche

jobs:
  build-and-deploy:
    runs-on: self-hosted
    container:
      image: node:20  # ou node:24 si tu préfères

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cd front_cesi_zen
          npm install
      - name: Build Quasar project
        run: |
          cd front_cesi_zen
          npm run build
          
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "$PRIVATE_DEPLOY_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 192.168.10.196 >> ~/.ssh/known_hosts
          echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
        env:
          PRIVATE_DEPLOY_KEY: ${{ secrets.PRIVATE_DEPLOY_KEY }}


      
      - name: Deploy front
        run: |
          scp -i ~/.ssh/id_ed25519 -r front/dist/spa/* hyrise@192.168.10.196:/var/www/html
          ssh -i ~/.ssh/id_ed25519 hyrise@192.168.10.196 'echo "✅ Déploiement terminé."'
