name: Deploy Quasar Front

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    container:
      image: node:20

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cd front_cesi_zen
          npm install

      - name: Build Quasar project
        run: |
          cd front_cesi_zen
          npm run build

      - name: Setup SSH
        run: |
          eval $(ssh-agent -s)
          echo "$PRIVATE_DEPLOY_KEY" | tr -d '\r' | ssh-add -
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -H 192.168.10.196 2>/dev/null >> ~/.ssh/known_hosts
        env:
          PRIVATE_DEPLOY_KEY: ${{ secrets.PRIVATE_DEPLOY_KEY }}

      - name: Deploy front
        run: |
          scp -i ~/.ssh/id_ed25519 -r front_cesi_zen/dist/spa/* hyrise@192.168.10.196:/var/www/html
          ssh -i ~/.ssh/id_ed25519 hyrise@192.168.10.196 'echo "✅ Déploiement terminé."'
